export enum Role {
  ROLE_ADMIN = 'ROLE_ADMIN',
  ROLE_OWNER = 'ROLE_OWNER',
  ROLE_MANAGER = 'ROLE_MANAGER',
  ROLE_ASSISTANT_MANAGER = 'ROLE_ASSISTANT_MANAGER',
  ROLE_TEAM_LEADER = 'ROLE_TEAM_LEADER',
  ROLE_EMPLOYEE = 'ROLE_EMPLOYEE',
}
